version: '3.9'

services:      
  server:
    container_name: practicum-server
    image: practicum-server
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      POSTGRES_HOST: 'postgres'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - awesome
    depends_on:
      - postgres
    command:
      ./utils/wait-for.sh postgres:${POSTGRES_PORT} -- node /app/index.js 

  postgres:
    image: postgres:14   
    restart: always  
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - awesome

  pgadmin:
    image: dpage/pgadmin4:6.19
    env_file:
      ./.env     
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - awesome

networks:
  awesome:
    driver: bridge

volumes:
  pg-data:
  pgadmin-data:
